version: "3.9"

services:
  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    container_name: ml-service
    ports:
      - "8000:8000"
    environment:
      - TZ=${TZ}
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - ai-trade-net

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "${N8N_PORT:-5678}:5678"
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=5678
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - GENERIC_TIMEZONE=${TZ}
      - TZ=${TZ}
      # Disable telemetry if you prefer:
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_TELEMETRY_ENABLED=false
    volumes:
      - n8n_data:/home/node/.n8n
      # optional: if you like to keep the workflow JSON handy in the container
      - ./workflows:/data/workflows:ro
    depends_on:
      ml-service:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - ai-trade-net

networks:
  ai-trade-net:

volumes:
  n8n_data:
