export default function PlanPage(){
  return (
    <div className="grid gap-6">
      <h1 className="h1">Action Plan</h1>
      <div className="card">This page will show weekly & monthly plan tasks generated by the coach (coming in Sprint 4).</div>
    </div>
  )
}
